[package]
name = "classfile"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
nom = { workspace = true }

java_constants = { workspace = true }

nom-derive = { version = "^0.10", default-features = false }
