[package]
name = "classfile"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
nom = { workspace = true }

bitflags = { version = "^2.4", default-features = false }
nom-derive = { version = "^0.10", default-features = false }
