[package]
name = "java_runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytemuck = { workspace = true }
dyn-clone = { workspace = true }
tracing = { workspace = true }

zip = { version = "^0.6", default-features = false }

java_class_proto = { workspace = true }
java_constants = { workspace = true }
jvm = { workspace = true }

[dev-dependencies]
futures-test = { workspace = true }
jvm_rust = { workspace = true }
