[package]
name = "java_runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
dyn-clone = { workspace = true }
tracing = { workspace = true }

bytemuck = { version = "^1.14", default-features = false, features = ["extern_crate_alloc"] }

java_runtime_base = { path = "../java_runtime_base" }
jvm = { path = "../jvm" }

[dev-dependencies]
futures-test = { workspace = true }
test_utils = { path = "../test_utils" }
