[workspace]
members = ["classfile"]

[package]
name = "jvm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "^1.0" }
tracing = { version = "^0.1" }

classfile = { path = "./classfile" }
