[package]
name = "jvm_tests"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { version = "^1.0" }

jvm = { path = "../jvm" }
jvm_impl = { path = "../jvm_impl" }

[dev-dependencies]
futures-test = { version = "^0.3" }
