[package]
name = "jvm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { version = "^1.0" }
tracing = { version = "^0.1" }

classfile = { path = "../classfile" }
