[package]
name = "jvm"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints.clippy]
await_holding_refcell_ref = "allow" # There's false positives https://github.com/rust-lang/rust-clippy/issues/6353

[dependencies]
anyhow = { version = "^1.0", default-features = false }
async-trait = { version = "^0.1", default-features = false }    
nom = { version = "^7.1", default-features = false }
tracing = { version = "^0.1", default-features = false }
