[package]
name = "jvm"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints.clippy]
await_holding_refcell_ref = "allow" # There's false positives https://github.com/rust-lang/rust-clippy/issues/6353

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytemuck = { workspace = true }
dyn-clone = { workspace = true }
nom = { workspace = true }
tracing = { workspace = true }

async-recursion = { version = "^1.0" }

java_constants = { workspace = true }
