[package]
name = "jvm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { version = "^1.0", default-features = false }
tracing = { version = "^0.1", default-features = false }
