[package]
name = "java_class_proto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
dyn-clone = { workspace = true }

jvm = { path = "../jvm" }
